#!/bin/sh

# key bindings
sxhkd &

# wallpaper
nitrogen --restore &

timidity -iA &

# set super key to launch rofi
ksuperkey -e 'Super_L=Alt_L|F1' &

# launch compton
al-compositor --start &

# gnome polkit
lxpolkit &

# panel
sleep 1; polybar minimal-bar &
xdo above -t $(xdo id -n root) $(xdo id -n polybar)
# Set some bsp specific stuff
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config normal_border_color '#000000'
bspc config active_border_color '#e0563a'
bspc config focused_border_color '#e0563a'
#bspc config presel_feedback_color

bspc config border_width 4
bspc config window_gap 12
bspc config top_padding 18
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus false
bspc config focus-follow-pointer
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a thunar desktop='^1' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Galculator state=floating
bspc rule -a Void_Exit_Session state=floating layer=above
bspc rule -a Exit_Session state=floating layer=above
bspc rule -a Gpick state=floating
bspc rule -a Gimp state= floating
bspc rule -a polybar layer=normal
bspc config external_rules_command /home/guidofe/bin/windowprop.sh
